-- 0000_baseline — the legacy SHDElectronicServiceDB schema (52 tables) exactly as
-- produced by setupdata/convert.py, rewritten to be IDEMPOTENT so it can run on a
-- database that already holds the loaded dump (no-op) or on an empty one.
-- Re-runnable after every re-dump/reload. Data is NOT part of this migration:
-- load it with setupdata/load_supabase.sh.

-- ProductNoneSerial
CREATE TABLE IF NOT EXISTS product_none_serial (
    item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id integer,
    store_location_id integer,
    condition_id integer,
    capital_price numeric(18, 2),
    wholesale_price numeric(18, 2),
    retail_price numeric(18, 2),
    remark varchar(100),
    is_publish boolean,
    quantity_inspection integer,
    quantity_not_available integer,
    quantity_available integer,
    quantity_used integer,
    quantity_booking integer NOT NULL,
    quantity_loss integer,
    quantity_remain integer,
    PRIMARY KEY (item_id)
);

-- ProductSerial
CREATE TABLE IF NOT EXISTS product_serial (
    item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    serial_no varchar(100),
    product_id integer,
    store_location_id integer,
    condition_id integer,
    quantity integer NOT NULL,
    quantity_booking integer NOT NULL,
    capital_price numeric(18, 2),
    wholesale_price numeric(18, 2),
    retail_price numeric(18, 2),
    remark varchar(100),
    picture_file_name varchar(50),
    is_publish boolean,
    is_saled boolean,
    sale_out_hd_no varchar(50),
    is_active boolean,
    create_date timestamp,
    create_by integer,
    cancel_remark varchar(100),
    cancel_date timestamp,
    cancel_by integer,
    PRIMARY KEY (item_id)
);

-- MT_CITY
CREATE TABLE IF NOT EXISTS mt_city (
    city_id integer NOT NULL,
    name_en varchar(50) NOT NULL,
    name_th varchar(50) NOT NULL,
    region varchar(15) NOT NULL,
    PRIMARY KEY (city_id)
);

-- MT_DISTRICT
CREATE TABLE IF NOT EXISTS mt_district (
    city_id integer NOT NULL,
    district_id integer NOT NULL,
    name_en varchar(50) NOT NULL,
    name_th varchar(50) NOT NULL,
    postal_code varchar(10) NOT NULL,
    PRIMARY KEY (district_id)
);

-- Customer
CREATE TABLE IF NOT EXISTS customer (
    customer_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_code varchar(50),
    customer_card_id varchar(20),
    customer_name varchar(200),
    customer_address varchar(200),
    customer_address1 varchar(100),
    customer_address2 varchar(100),
    postal_code varchar(5),
    phone_number varchar(50),
    fax_number varchar(50),
    email varchar(50),
    customer_type varchar(50),
    created_date timestamp,
    create_by integer,
    is_active boolean,
    use_price_group varchar(50),
    line_id varchar(50),
    is_customer_online boolean,
    city_id integer,
    district_id integer,
    sub_district_id integer,
    PRIMARY KEY (customer_id)
);

-- MT_SUB_DISTRICT
CREATE TABLE IF NOT EXISTS mt_sub_district (
    city_id integer NOT NULL,
    district_id integer NOT NULL,
    sub_district_id integer NOT NULL,
    name_en varchar(50) NOT NULL,
    name_th varchar(50) NOT NULL,
    postal_code varchar(10) NOT NULL,
    PRIMARY KEY (sub_district_id)
);

-- AppBackUpDBLog
CREATE TABLE IF NOT EXISTS app_back_up_db_log (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    back_up_date timestamp,
    back_up_by integer,
    back_up_file_name varchar(100),
    PRIMARY KEY (id)
);

-- AppConfig
CREATE TABLE IF NOT EXISTS app_config (
    config_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_type varchar(50),
    module_name varchar(50),
    can_insert boolean,
    can_edit boolean,
    can_delete boolean,
    can_view boolean,
    PRIMARY KEY (config_id)
);

-- ApproveStatus
CREATE TABLE IF NOT EXISTS approve_status (
    approve_status_id integer NOT NULL,
    approve_name_th varchar(50),
    approve_name_en varchar(50),
    approve_description varchar(100),
    is_can_edit boolean,
    is_can_revise boolean,
    PRIMARY KEY (approve_status_id)
);

-- Category
CREATE TABLE IF NOT EXISTS category (
    category_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name varchar(50),
    category_description varchar(50),
    shot_code varchar(50),
    is_active boolean,
    PRIMARY KEY (category_id)
);

-- Color
CREATE TABLE IF NOT EXISTS color (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    color_name varchar(50),
    description varchar(100),
    is_active boolean,
    PRIMARY KEY (id)
);

-- Condition
CREATE TABLE IF NOT EXISTS condition (
    condition_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    condition_name varchar(50),
    condition_description varchar(100),
    is_active boolean,
    PRIMARY KEY (condition_id)
);

-- DocumentAttach
CREATE TABLE IF NOT EXISTS document_attach (
    document_attach_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reference_topic varchar(50),
    reference_item_code varchar(50),
    original_file_name varchar(50),
    system_file_name varchar(50),
    remark varchar(100),
    is_active boolean,
    PRIMARY KEY (document_attach_id)
);

-- InventoryDT
CREATE TABLE IF NOT EXISTS inventory_dt (
    inventory_dt_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inventory_no varchar(50),
    item_code varchar(50),
    item_quantity numeric(18, 4),
    item_unit varchar(50),
    store_location_id integer,
    stock_type_id integer,
    receive_inventory_no varchar(20),
    PRIMARY KEY (inventory_dt_id)
);

-- InventoryHD
CREATE TABLE IF NOT EXISTS inventory_hd (
    inventory_hd_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inventory_no varchar(50),
    inventory_type_id integer,
    item_type varchar(50),
    reference_document_no varchar(50),
    reference_out_to varchar(50),
    inventory_remark varchar(100),
    create_date timestamp,
    create_by integer,
    is_active boolean,
    company_id integer,
    branch_id integer,
    PRIMARY KEY (inventory_hd_id)
);

-- InventoryType
CREATE TABLE IF NOT EXISTS inventory_type (
    inventory_type_id integer NOT NULL,
    inventory_type_name varchar(50),
    movement_action_type varchar(50),
    movement_action integer,
    effect_material boolean,
    effect_package boolean,
    effect_product boolean,
    remark varchar(100),
    is_active boolean,
    PRIMARY KEY (inventory_type_id)
);

-- Job
CREATE TABLE IF NOT EXISTS job (
    job_no varchar(50) NOT NULL,
    company_id integer,
    branch_id integer,
    customer_id integer,
    customer_detail varchar(200),
    customer_due_date timestamp,
    job_create_date timestamp,
    job_create_by integer,
    job_type_id integer,
    job_type_detail varchar(50),
    job_status_id integer,
    job_repaired_date timestamp,
    job_repaired_by integer,
    job_closed_date timestamp,
    job_closed_by integer,
    product_imei_no varchar(50),
    product_serial varchar(50),
    product_type_id integer,
    product_brand_id integer,
    product_model_id integer,
    product_model_name varchar(50),
    product_model_detail varchar(200),
    product_color varchar(50),
    product_symptom_id integer,
    product_symptom_other varchar(200),
    product_equipment varchar(100),
    product_fault varchar(100),
    estimate_cost numeric(18, 2),
    deposit_cost numeric(18, 2),
    spare_part_total_cost numeric(18, 2),
    service_cost numeric(18, 2),
    service_tool_cost numeric(18, 2),
    delivery_cost numeric(18, 2),
    carton_box_cost numeric(18, 2),
    job_total_cost numeric(18, 2),
    job_reference_no varchar(50),
    job_reference_no_gspn varchar(50),
    job_gspn_create_date timestamp,
    job_remark text,
    engineer_id integer,
    engineer_symptom_id integer,
    engineer_repair_detail varchar(200),
    engineer_remark varchar(200),
    job_payment_type varchar(50),
    job_payment_no varchar(50),
    job_payment_amount numeric(18, 2),
    job_payment_detail varchar(100),
    job_return_date timestamp,
    return_customer_type varchar(50),
    return_customer_tracking_no varchar(50),
    return_customer_detail varchar(100),
    job_return_by integer,
    spare_part_replace varchar(300),
    product_warranty varchar(50),
    quotation_no_approved varchar(50),
    product_sale_out_channel varchar(50),
    product_sale_order_date date,
    product_warranty_month integer,
    product_expire_date date,
    job_reception_type varchar(50),
    job_reception_date date,
    job_reception_tracking_no varchar(50),
    job_reception_shipper varchar(50),
    swap_refund_detail text,
    job_payment_slip_file_name varchar(100),
    swap_refund_document_no varchar(100),
    is_job_bounce boolean,
    product_sale_out_shop_name varchar(100),
    PRIMARY KEY (job_no)
);

-- JobCallLog
CREATE TABLE IF NOT EXISTS job_call_log (
    job_call_log_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_no varchar(50),
    call_log_description varchar(200),
    call_log_date timestamp,
    call_log_by integer,
    PRIMARY KEY (job_call_log_id)
);

-- JobCloseTemp
CREATE TABLE IF NOT EXISTS job_close_temp (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    serial_no varchar(50),
    is_can_close_job boolean,
    ref_job_no varchar(50),
    next_status_id integer,
    remark varchar(50),
    PRIMARY KEY (id)
);

-- JobCreateTemp
CREATE TABLE IF NOT EXISTS job_create_temp (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_imei_no varchar(50),
    lot_no varchar(50),
    model_code varchar(50),
    warranty varchar(50),
    is_can_generate_job boolean,
    remark varchar(200),
    product_serial varchar(50),
    product_model_detail varchar(50),
    job_reference_no_gspn varchar(50),
    PRIMARY KEY (id)
);

-- JobLog
CREATE TABLE IF NOT EXISTS job_log (
    job_log_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_no varchar(50),
    job_status_id integer,
    job_log_date timestamp,
    job_action_by integer,
    PRIMARY KEY (job_log_id)
);

-- JobOrderSparePartLog
CREATE TABLE IF NOT EXISTS job_order_spare_part_log (
    job_order_log_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_no varchar(50),
    spare_part_code varchar(50),
    spare_part_unit_price numeric(18, 2),
    spare_part_serial_no varchar(50),
    stock_id integer,
    is_quotation boolean,
    is_special boolean,
    request_qty integer,
    spare_part_total_price numeric(18, 2),
    is_quotation_b boolean,
    is_special_b boolean,
    request_qty_b integer,
    spare_part_total_price_b numeric(18, 2),
    order_status_id integer,
    request_date timestamp,
    request_by integer,
    grant_qty integer,
    grant_date timestamp,
    grant_by integer,
    return_qty integer,
    return_date timestamp,
    return_by integer,
    return_stock_id integer,
    PRIMARY KEY (job_order_log_id)
);

-- JobOrderSparePartStatus
CREATE TABLE IF NOT EXISTS job_order_spare_part_status (
    order_status_id integer NOT NULL,
    order_status_name varchar(50),
    order_status_description varchar(50),
    PRIMARY KEY (order_status_id)
);

-- JobReturnDT
CREATE TABLE IF NOT EXISTS job_return_dt (
    job_return_dt_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    return_no varchar(50),
    item_no varchar(50),
    end_user_name varchar(100),
    reference_job_no varchar(50),
    product_model_name varchar(50),
    product_serial_no varchar(50),
    equipment_return varchar(100),
    PRIMARY KEY (job_return_dt_id)
);

-- JobReturnHD
CREATE TABLE IF NOT EXISTS job_return_hd (
    job_return_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    return_date timestamp,
    return_customer_name varchar(100),
    original_file_name varchar(50),
    system_file_name varchar(50),
    create_date timestamp,
    create_by integer,
    return_customer_code varchar(50),
    return_no varchar(50),
    image_file_name varchar(50),
    PRIMARY KEY (job_return_id)
);

-- JobSendForwardDT
CREATE TABLE IF NOT EXISTS job_send_forward_dt (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_no varchar(50),
    send_to_name varchar(50),
    send_detail varchar(100),
    send_date timestamp,
    send_by integer,
    receive_date timestamp,
    receive_by integer,
    receive_detail varchar(100),
    send_status varchar(50),
    PRIMARY KEY (id)
);

-- JobServiceCode
CREATE TABLE IF NOT EXISTS job_service_code (
    service_code varchar(50) NOT NULL,
    service_name varchar(50),
    service_description varchar(50),
    PRIMARY KEY (service_code)
);

-- JobStatus
CREATE TABLE IF NOT EXISTS job_status (
    job_status_id integer NOT NULL,
    job_status_name varchar(100),
    display_order integer,
    job_status_group varchar(50),
    is_active boolean,
    PRIMARY KEY (job_status_id)
);

-- JobType
CREATE TABLE IF NOT EXISTS job_type (
    job_type_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_type_name varchar(50),
    job_type_description varchar(100),
    is_active boolean,
    PRIMARY KEY (job_type_id)
);

-- Manufacturer
CREATE TABLE IF NOT EXISTS manufacturer (
    manufacturer_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    manufacturer_name varchar(50),
    logo_name varchar(50),
    is_active boolean,
    PRIMARY KEY (manufacturer_id)
);

-- Model
CREATE TABLE IF NOT EXISTS model (
    model_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model_code varchar(50),
    model_name varchar(50),
    market_price numeric(18, 2),
    manufacturer_id integer,
    is_active boolean,
    tier_id integer,
    last_update timestamp,
    PRIMARY KEY (model_id)
);

-- ModelColor
CREATE TABLE IF NOT EXISTS model_color (
    item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model_name varchar(50),
    color_name varchar(100),
    default_color varchar(50),
    exten_file_name varchar(50),
    is_active boolean,
    PRIMARY KEY (item_id)
);

-- ModelPart
CREATE TABLE IF NOT EXISTS model_part (
    item_price_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model_item_id integer,
    color varchar(50),
    part_name varchar(50),
    price numeric(18, 2),
    service numeric(18, 2),
    remark varchar(50),
    PRIMARY KEY (item_price_id)
);

-- ModelTier
CREATE TABLE IF NOT EXISTS model_tier (
    tier_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tier_no varchar(50),
    min_price numeric(18, 2),
    max_price numeric(18, 2),
    rrp_percent numeric(18, 2),
    PRIMARY KEY (tier_id)
);

-- Product
CREATE TABLE IF NOT EXISTS product (
    product_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_code varchar(50),
    product_vender_code varchar(50),
    product_name varchar(500),
    product_name_en varchar(200),
    product_name_cn varchar(200),
    product_description varchar(200),
    category_id integer,
    manufacturer_id integer,
    is_serial_control boolean,
    pictrue_file_name varchar(50),
    is_active boolean,
    create_date timestamp,
    create_by integer,
    cancel_remark varchar(100),
    cancel_date timestamp,
    cancel_by integer,
    is_ub_repair_only boolean,
    for_model_color varchar(50),
    PRIMARY KEY (product_id)
);

-- ProductModel
CREATE TABLE IF NOT EXISTS product_model (
    product_model_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id integer,
    model_code varchar(50),
    PRIMARY KEY (product_model_id)
);

-- ProductType
CREATE TABLE IF NOT EXISTS product_type (
    product_type_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_type_name varchar(50),
    is_active boolean,
    PRIMARY KEY (product_type_id)
);

-- QuotationDT
CREATE TABLE IF NOT EXISTS quotation_dt (
    quotation_dt_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quotation_no varchar(50),
    line_number integer,
    item_type varchar(50),
    item_code varchar(50),
    item_detail varchar(100),
    quantity varchar(10),
    unit varchar(10),
    unit_price varchar(20),
    unit_price_discount varchar(20),
    total_price varchar(20),
    unit_price_discount_percent varchar(20),
    PRIMARY KEY (quotation_dt_id)
);

-- QuotationHD
CREATE TABLE IF NOT EXISTS quotation_hd (
    quotation_hd_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quotation_no varchar(50),
    customer_code varchar(50),
    customer_contact_name varchar(100),
    create_date timestamp,
    create_by integer,
    spare_part_amount numeric(19,4),
    service_amount numeric(19,4),
    sum_exclude_amount numeric(19,4),
    discount_type varchar(50),
    discount_formula varchar(100),
    discount_amount numeric(19,4),
    after_discount_amount numeric(19,4),
    total_base_amount numeric(19,4),
    vat_rate double precision,
    vat_amount numeric(19,4),
    total_amount numeric(19,4),
    rounding_amount numeric(19,4),
    net_amount numeric(19,4),
    remark text,
    reference_job_no varchar(50),
    quotation_status_id integer,
    customer_approve_date timestamp,
    customer_approve_remark varchar(100),
    is_active boolean,
    quotation_type varchar(50),
    PRIMARY KEY (quotation_hd_id)
);

-- QuotationStatus
CREATE TABLE IF NOT EXISTS quotation_status (
    quotation_status_id integer NOT NULL,
    quotation_status_name varchar(50) NOT NULL,
    PRIMARY KEY (quotation_status_id)
);

-- QuotationTemp
CREATE TABLE IF NOT EXISTS quotation_temp (
    quotation_no varchar(50) NOT NULL,
    is_can_edit boolean,
    PRIMARY KEY (quotation_no)
);

-- RunningNo
CREATE TABLE IF NOT EXISTS running_no (
    running_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    running_type varchar(50) NOT NULL,
    company_id integer NOT NULL,
    branch_id integer NOT NULL,
    prefix varchar(10) NOT NULL,
    pyear integer NOT NULL,
    pmonth integer NOT NULL,
    pday integer NOT NULL,
    number integer NOT NULL,
    length_year integer NOT NULL,
    length_month integer NOT NULL,
    length_number integer NOT NULL,
    PRIMARY KEY (running_id)
);

-- SaleInDT
CREATE TABLE IF NOT EXISTS sale_in_dt (
    sale_in_dt_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sale_in_hd_no varchar(50),
    list_no integer,
    product_id integer,
    store_location_id integer,
    condition_id integer,
    serial_no varchar(50),
    quantity_at_current integer,
    quantity_income integer,
    capital_price numeric(18, 2),
    wholesale_price numeric(18, 2),
    retail_price numeric(18, 2),
    remark varchar(100),
    PRIMARY KEY (sale_in_dt_id)
);

-- SaleInHD
CREATE TABLE IF NOT EXISTS sale_in_hd (
    sale_in_hd_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sale_in_hd_no varchar(50),
    sale_in_type varchar(50),
    sale_in_date timestamp,
    sale_in_by integer,
    PRIMARY KEY (sale_in_hd_id)
);

-- SaleOutDT
CREATE TABLE IF NOT EXISTS sale_out_dt (
    sale_out_dt_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sale_out_hd_no varchar(50),
    list_no integer,
    product_id integer,
    store_location_id integer,
    condition_id integer,
    serial_no varchar(50),
    capital_price numeric(18, 2),
    wholesale_price numeric(18, 2),
    retail_price numeric(18, 2),
    sale_out_price numeric(18, 2),
    sale_out_quantity integer NOT NULL,
    amount_dt numeric(18, 2),
    remark_dt varchar(100),
    onhand_item_id integer,
    product_type varchar(50),
    document_credit_note_no varchar(50),
    product_code varchar(50),
    pick_inventory_no varchar(50),
    return_inventory_no varchar(50),
    PRIMARY KEY (sale_out_dt_id)
);

-- SaleOutHD
CREATE TABLE IF NOT EXISTS sale_out_hd (
    sale_out_hd_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sale_out_hd_no varchar(50),
    document_type varchar(50),
    document_create_date timestamp,
    document_create_by integer,
    document_status boolean,
    document_credit_note_no varchar(100),
    document_cancel_date timestamp,
    document_cancel_by integer,
    document_cancel_remark varchar(100),
    customer_id integer,
    customer_code varchar(50),
    customer_card_id varchar(50),
    customer_name varchar(200),
    customer_address varchar(500),
    customer_phone_number varchar(50),
    customer_fax_number varchar(50),
    total_base_amount numeric(18, 2),
    vat_rat numeric(18, 2),
    vat_amount numeric(18, 2),
    total_amount numeric(18, 2),
    rounding_amount numeric(18, 2),
    fee_amount numeric(18, 2),
    net_amount numeric(18, 2),
    remark_hd varchar(100),
    is_sale_out boolean,
    sale_out_date timestamp,
    sale_out_by integer,
    reference_no varchar(50),
    payment_type varchar(50),
    payment_amount numeric(11, 2),
    slip_file_name varchar(100),
    approve_status_id integer,
    approve_date timestamp,
    approve_by integer,
    approve_remark varchar(100),
    delivery_tracking_no varchar(50),
    delivery_date timestamp,
    PRIMARY KEY (sale_out_hd_id)
);

-- ServiceCost
CREATE TABLE IF NOT EXISTS service_cost (
    service_code varchar(50) NOT NULL,
    service_description varchar(100),
    service_cost numeric(18, 2),
    PRIMARY KEY (service_code)
);

-- StoreLocation
CREATE TABLE IF NOT EXISTS store_location (
    store_location_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_location_name varchar(50),
    store_location_description varchar(50),
    store_location_group varchar(50),
    is_active boolean,
    PRIMARY KEY (store_location_id)
);

-- Symptom
CREATE TABLE IF NOT EXISTS symptom (
    symptom_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    symptom_name varchar(50),
    symptom_description varchar(100),
    symptom_group_name varchar(50),
    is_active boolean,
    PRIMARY KEY (symptom_id)
);

-- TempModel
CREATE TABLE IF NOT EXISTS temp_model (
    id integer,
    model_name varchar(50),
    model_code varchar(50),
    market_price numeric(18, 2)
);

-- TempSparePart
CREATE TABLE IF NOT EXISTS temp_spare_part (
    item_id integer,
    product_vender_code varchar(50),
    spare_part_name_th varchar(100),
    spare_part_name_en varchar(100),
    spare_part_name_cn varchar(100),
    spare_part_description varchar(200),
    manufacturer_name varchar(50),
    quantity_remain integer,
    capital_price numeric(18, 2),
    retail_price numeric(18, 2)
);

-- User
CREATE TABLE IF NOT EXISTS app_user (
    user_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username varchar(50),
    password varchar(50),
    first_name varchar(50),
    last_name varchar(50),
    user_type varchar(50),
    is_active boolean,
    phone_no varchar(50),
    email_address varchar(100),
    asc_code varchar(50),
    asc_name varchar(50),
    PRIMARY KEY (user_id)
);


-- indexes
CREATE UNIQUE INDEX IF NOT EXISTS ix_user_type_and_module_name ON app_config (user_type, module_name);
CREATE UNIQUE INDEX IF NOT EXISTS ix_category_name ON category (category_name);
CREATE UNIQUE INDEX IF NOT EXISTS ix_customer_code ON customer (customer_code);
CREATE INDEX IF NOT EXISTS ix_job_no ON job_order_spare_part_log (job_no);
CREATE UNIQUE INDEX IF NOT EXISTS ix_job_type_name ON job_type (job_type_name);
CREATE UNIQUE INDEX IF NOT EXISTS ix_manufacturer_name ON manufacturer (manufacturer_name);
CREATE UNIQUE INDEX IF NOT EXISTS ix_unique_model ON model (model_name, manufacturer_id, is_active);
CREATE UNIQUE INDEX IF NOT EXISTS ix_product_type_name ON product_type (product_type_name);
CREATE INDEX IF NOT EXISTS ix_quotation_dt_quotation_no ON quotation_dt (quotation_no);
CREATE INDEX IF NOT EXISTS ix_quotation_hd_create_date ON quotation_hd (create_date);
CREATE INDEX IF NOT EXISTS ix_quotation_hd_customer_code ON quotation_hd (customer_code);
CREATE INDEX IF NOT EXISTS ix_quotation_hd_reference_job_no ON quotation_hd (reference_job_no);
CREATE UNIQUE INDEX IF NOT EXISTS ix_store_location_name ON store_location (store_location_name);
CREATE UNIQUE INDEX IF NOT EXISTS ix_username_and_password ON app_user (username, password);

-- foreign keys (guarded)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mt_district_mt_city') THEN
    ALTER TABLE mt_district ADD CONSTRAINT fk_mt_district_mt_city FOREIGN KEY (city_id) REFERENCES mt_city (city_id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mt_sub_district_mt_city') THEN
    ALTER TABLE mt_sub_district ADD CONSTRAINT fk_mt_sub_district_mt_city FOREIGN KEY (city_id) REFERENCES mt_city (city_id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mt_sub_district_mt_district') THEN
    ALTER TABLE mt_sub_district ADD CONSTRAINT fk_mt_sub_district_mt_district FOREIGN KEY (district_id) REFERENCES mt_district (district_id);
  END IF;
END $$;

-- views
CREATE OR REPLACE VIEW view_customer AS
SELECT c.customer_id, c.customer_code, c.customer_card_id, c.customer_name,
       c.customer_address, c.customer_address1, c.customer_address2, c.postal_code,
       c.phone_number, c.fax_number, c.email, c.customer_type,
       c.created_date, c.create_by, c.is_active, c.use_price_group, c.line_id,
       c.is_customer_online, c.city_id, c.district_id, c.sub_district_id,
       CASE WHEN c.city_id = 10 THEN p.name_th  ELSE 'จ.' || p.name_th  END AS province_name,
       CASE WHEN c.city_id = 10 THEN d.name_th  ELSE 'อ.' || d.name_th  END AS ampher_name,
       CASE WHEN c.city_id = 10 THEN sd.name_th ELSE 'ต.' || sd.name_th END AS tambon_name
FROM customer AS c
LEFT OUTER JOIN mt_city         AS p  ON p.city_id = c.city_id
LEFT OUTER JOIN mt_district     AS d  ON d.city_id = c.city_id AND d.district_id = c.district_id
LEFT OUTER JOIN mt_sub_district AS sd ON sd.city_id = c.city_id AND sd.district_id = c.district_id
                                     AND sd.sub_district_id = c.sub_district_id;

-- column comments
COMMENT ON COLUMN quotation_hd.sum_exclude_amount IS 'รวมเงิน (ก่อนภาษี)';
COMMENT ON COLUMN quotation_hd.discount_formula IS 'สูตรของส่วนลดการค้า';
COMMENT ON COLUMN quotation_hd.discount_amount IS 'จำนวนเงินส่วนลดการค้า';
COMMENT ON COLUMN quotation_hd.after_discount_amount IS 'จำนวนเงินหลังหักส่วนลดการค้า';
COMMENT ON COLUMN quotation_hd.total_base_amount IS 'ฐานภาษี';
COMMENT ON COLUMN quotation_hd.vat_rate IS 'ภาษีมูลค่าเพิ่ม';
COMMENT ON COLUMN quotation_hd.vat_amount IS 'จำนวนเงิน ภาษีมูลค่าเพิ่ม';
COMMENT ON COLUMN quotation_hd.total_amount IS 'จำนวนเงินทั้งสิ้น ก่อนปัดเศษ';
COMMENT ON COLUMN quotation_hd.rounding_amount IS 'จำนวนเงินปัดเศษ';
COMMENT ON COLUMN quotation_hd.net_amount IS 'จำนวนเงินทั้งสิ้น';

-- identity sequences → max(id)+1 (safe to re-run)
SELECT setval(pg_get_serial_sequence('product_none_serial', 'item_id'), COALESCE((SELECT max(item_id) FROM product_none_serial), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('product_serial', 'item_id'), COALESCE((SELECT max(item_id) FROM product_serial), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('customer', 'customer_id'), COALESCE((SELECT max(customer_id) FROM customer), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('app_back_up_db_log', 'id'), COALESCE((SELECT max(id) FROM app_back_up_db_log), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('app_config', 'config_id'), COALESCE((SELECT max(config_id) FROM app_config), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('category', 'category_id'), COALESCE((SELECT max(category_id) FROM category), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('color', 'id'), COALESCE((SELECT max(id) FROM color), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('condition', 'condition_id'), COALESCE((SELECT max(condition_id) FROM condition), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('document_attach', 'document_attach_id'), COALESCE((SELECT max(document_attach_id) FROM document_attach), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('inventory_dt', 'inventory_dt_id'), COALESCE((SELECT max(inventory_dt_id) FROM inventory_dt), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('inventory_hd', 'inventory_hd_id'), COALESCE((SELECT max(inventory_hd_id) FROM inventory_hd), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('job_call_log', 'job_call_log_id'), COALESCE((SELECT max(job_call_log_id) FROM job_call_log), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('job_close_temp', 'id'), COALESCE((SELECT max(id) FROM job_close_temp), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('job_create_temp', 'id'), COALESCE((SELECT max(id) FROM job_create_temp), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('job_log', 'job_log_id'), COALESCE((SELECT max(job_log_id) FROM job_log), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('job_order_spare_part_log', 'job_order_log_id'), COALESCE((SELECT max(job_order_log_id) FROM job_order_spare_part_log), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('job_return_dt', 'job_return_dt_id'), COALESCE((SELECT max(job_return_dt_id) FROM job_return_dt), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('job_return_hd', 'job_return_id'), COALESCE((SELECT max(job_return_id) FROM job_return_hd), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('job_send_forward_dt', 'id'), COALESCE((SELECT max(id) FROM job_send_forward_dt), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('job_type', 'job_type_id'), COALESCE((SELECT max(job_type_id) FROM job_type), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('manufacturer', 'manufacturer_id'), COALESCE((SELECT max(manufacturer_id) FROM manufacturer), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('model', 'model_id'), COALESCE((SELECT max(model_id) FROM model), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('model_color', 'item_id'), COALESCE((SELECT max(item_id) FROM model_color), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('model_part', 'item_price_id'), COALESCE((SELECT max(item_price_id) FROM model_part), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('model_tier', 'tier_id'), COALESCE((SELECT max(tier_id) FROM model_tier), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('product', 'product_id'), COALESCE((SELECT max(product_id) FROM product), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('product_model', 'product_model_id'), COALESCE((SELECT max(product_model_id) FROM product_model), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('product_type', 'product_type_id'), COALESCE((SELECT max(product_type_id) FROM product_type), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('quotation_dt', 'quotation_dt_id'), COALESCE((SELECT max(quotation_dt_id) FROM quotation_dt), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('quotation_hd', 'quotation_hd_id'), COALESCE((SELECT max(quotation_hd_id) FROM quotation_hd), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('running_no', 'running_id'), COALESCE((SELECT max(running_id) FROM running_no), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('sale_in_dt', 'sale_in_dt_id'), COALESCE((SELECT max(sale_in_dt_id) FROM sale_in_dt), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('sale_in_hd', 'sale_in_hd_id'), COALESCE((SELECT max(sale_in_hd_id) FROM sale_in_hd), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('sale_out_dt', 'sale_out_dt_id'), COALESCE((SELECT max(sale_out_dt_id) FROM sale_out_dt), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('sale_out_hd', 'sale_out_hd_id'), COALESCE((SELECT max(sale_out_hd_id) FROM sale_out_hd), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('store_location', 'store_location_id'), COALESCE((SELECT max(store_location_id) FROM store_location), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('symptom', 'symptom_id'), COALESCE((SELECT max(symptom_id) FROM symptom), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('app_user', 'user_id'), COALESCE((SELECT max(user_id) FROM app_user), 0) + 1, false);

-- RLS on: the app talks to Postgres directly (drizzle); PostgREST/anon must not read these tables
ALTER TABLE product_none_serial ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_serial ENABLE ROW LEVEL SECURITY;
ALTER TABLE mt_city ENABLE ROW LEVEL SECURITY;
ALTER TABLE mt_district ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer ENABLE ROW LEVEL SECURITY;
ALTER TABLE mt_sub_district ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_back_up_db_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE approve_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE category ENABLE ROW LEVEL SECURITY;
ALTER TABLE color ENABLE ROW LEVEL SECURITY;
ALTER TABLE condition ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_attach ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_dt ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_hd ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_type ENABLE ROW LEVEL SECURITY;
ALTER TABLE job ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_call_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_close_temp ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_create_temp ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_order_spare_part_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_order_spare_part_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_return_dt ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_return_hd ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_send_forward_dt ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_service_code ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_type ENABLE ROW LEVEL SECURITY;
ALTER TABLE manufacturer ENABLE ROW LEVEL SECURITY;
ALTER TABLE model ENABLE ROW LEVEL SECURITY;
ALTER TABLE model_color ENABLE ROW LEVEL SECURITY;
ALTER TABLE model_part ENABLE ROW LEVEL SECURITY;
ALTER TABLE model_tier ENABLE ROW LEVEL SECURITY;
ALTER TABLE product ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_model ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_type ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotation_dt ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotation_hd ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotation_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotation_temp ENABLE ROW LEVEL SECURITY;
ALTER TABLE running_no ENABLE ROW LEVEL SECURITY;
ALTER TABLE sale_in_dt ENABLE ROW LEVEL SECURITY;
ALTER TABLE sale_in_hd ENABLE ROW LEVEL SECURITY;
ALTER TABLE sale_out_dt ENABLE ROW LEVEL SECURITY;
ALTER TABLE sale_out_hd ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_cost ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_location ENABLE ROW LEVEL SECURITY;
ALTER TABLE symptom ENABLE ROW LEVEL SECURITY;
ALTER TABLE temp_model ENABLE ROW LEVEL SECURITY;
ALTER TABLE temp_spare_part ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_user ENABLE ROW LEVEL SECURITY;
